# Generated by Django 3.0 on 2020-10-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USDistrict',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
            ],
            options={
                'verbose_name': 'us district',
                'verbose_name_plural': 'us districts',
                'db_table': 'fec_us_district',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
