# Generated by Django 3.0 on 2020-10-04 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('us_district', '0001_initial'),
        ('us_state', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usdistrict',
            name='state',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usdistrict_relation', to='us_state.USState'),
        ),
    ]
