# Generated by Django 3.0 on 2020-10-04 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('us_state', '0001_initial'),
        ('us_district', '0002_usdistrict_state'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usdistrict',
            unique_together={('state', 'name')},
        ),
    ]
