# Generated by Django 3.2.5 on 2021-07-13 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('political_office', '0001_initial'),
        ('political_party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('candidate_id', models.CharField(max_length=256, null=True)),
                ('first_name', models.CharField(max_length=256, null=True)),
                ('last_name', models.CharField(max_length=256, null=True)),
                ('office', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidate_relation', to='political_office.politicaloffice')),
                ('party', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidate_relation', to='political_party.politicalparty')),
            ],
            options={
                'verbose_name': 'candidate',
                'verbose_name_plural': 'candidates',
                'db_table': 'fec_candidate',
                'ordering': ['first_name', 'last_name'],
                'abstract': False,
            },
        ),
    ]
