# Generated by Django 3.0 on 2020-09-20 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='district_number',
            new_name='district',
        ),
    ]
