# Generated by Django 3.0 on 2020-09-20 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_auto_20190520_0649'),
        ('candidate', '0002_auto_20200919_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'candidate', 'verbose_name_plural': 'candidates'},
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('environment', 'candidate_id')},
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='name',
        ),
    ]
