# Generated by Django 3.0 on 2020-10-04 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_auto_20200920_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='district',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='office',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='party',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='state',
        ),
    ]
