# Generated by Django 3.0 on 2020-10-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_auto_20201004_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='office',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
