# Generated by Django 3.2.5 on 2021-07-13 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0001_initial'),
        ('year', '0001_initial'),
        ('political_party', '0001_initial'),
        ('us_state', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('committee_id', models.CharField(max_length=256, null=True)),
                ('type', models.CharField(max_length=256, null=True)),
                ('designation', models.CharField(max_length=256, null=True)),
                ('filing_frequency', models.CharField(max_length=256, null=True)),
                ('candidates', models.ManyToManyField(related_name='committee_relations', to='candidate.Candidate')),
                ('party', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='committee_relation', to='political_party.politicalparty')),
                ('state', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='committee_relation', to='us_state.usstate')),
                ('years', models.ManyToManyField(related_name='committee_relations', to='year.Year')),
            ],
            options={
                'verbose_name': 'committee',
                'verbose_name_plural': 'committees',
                'db_table': 'fec_committee',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
