# Generated by Django 3.0 on 2020-09-20 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0003_auto_20200920_0108'),
        ('environment', '0002_auto_20190520_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('committee_id', models.CharField(max_length=256, null=True)),
                ('type', models.CharField(max_length=256, null=True)),
                ('designation', models.CharField(max_length=256, null=True)),
                ('filing_frequency', models.CharField(max_length=256, null=True)),
                ('state', models.CharField(max_length=256, null=True)),
                ('party', models.CharField(max_length=256, null=True)),
                ('candidates', models.ManyToManyField(related_name='committee_relations', to='candidate.Candidate')),
                ('environment', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='committee_relation', to='environment.Environment')),
            ],
            options={
                'verbose_name': 'committee',
                'verbose_name_plural': 'committees',
                'db_table': 'fec_committee',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('environment', 'committee_id')},
            },
        ),
    ]
