# Generated by Django 3.0 on 2020-10-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidacy', '0004_auto_20201004_1343'),
        ('committee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='candidacies',
            field=models.ManyToManyField(related_name='committee_relations', to='candidacy.Candidacy'),
        ),
    ]
