# Generated by Django 3.0 on 2020-10-04 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('political_party', '0001_initial'),
        ('us_state', '0001_initial'),
        ('committee', '0002_committee_candidacies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='party',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='committee_relation', to='political_party.PoliticalParty'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='state',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='committee_relation', to='us_state.USState'),
        ),
    ]
