# Generated by Django 3.0 on 2020-10-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0003_auto_20201004_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='candidacies',
        ),
    ]
