# Generated by Django 3.2.4 on 2021-07-11 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0005_committee_years'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='committee',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='committee',
            name='environment',
        ),
    ]
