# Generated by Django 3.0 on 2020-10-04 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0004_auto_20201004_0948'),
        ('us_district', '0002_usdistrict_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidacy',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('candidacy_id', models.CharField(max_length=256, null=True)),
                ('office', models.CharField(max_length=256, null=True)),
                ('year', models.IntegerField(null=True)),
                ('elected', models.BooleanField(default=False)),
                ('party', models.CharField(max_length=256, null=True)),
                ('candidate', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidacy_relation', to='candidate.Candidate')),
                ('district', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidacy_relation', to='us_district.USDistrict')),
            ],
            options={
                'verbose_name': 'candidacy',
                'verbose_name_plural': 'candidacies',
                'db_table': 'fec_candidacy',
                'ordering': ['office', '-year'],
                'abstract': False,
                'unique_together': {('candidate', 'candidacy_id')},
            },
        ),
    ]
