# Generated by Django 3.2.5 on 2021-07-13 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0001_initial'),
        ('year', '0001_initial'),
        ('us_district', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidacy',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('candidacy_id', models.CharField(max_length=256, null=True)),
                ('candidate', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidacy_relation', to='candidate.candidate')),
                ('district', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidacy_relation', to='us_district.usdistrict')),
                ('year', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidacy_relation', to='year.year')),
            ],
            options={
                'verbose_name': 'candidacy',
                'verbose_name_plural': 'candidacies',
                'db_table': 'fec_candidacy',
                'ordering': ['-year__name'],
                'abstract': False,
                'unique_together': {('candidate', 'candidacy_id')},
            },
        ),
    ]
