# Generated by Django 3.0 on 2020-10-04 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidacy',
            name='elected',
        ),
    ]
