# Generated by Django 3.0 on 2020-10-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidacy', '0002_remove_candidacy_elected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidacy',
            options={'ordering': ['-year'], 'verbose_name': 'candidacy', 'verbose_name_plural': 'candidacies'},
        ),
        migrations.RemoveField(
            model_name='candidacy',
            name='office',
        ),
        migrations.RemoveField(
            model_name='candidacy',
            name='party',
        ),
    ]
