# Generated by Django 3.0 on 2020-10-04 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidacy', '0003_auto_20201004_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidacy',
            options={'ordering': ['-year__name'], 'verbose_name': 'candidacy', 'verbose_name_plural': 'candidacies'},
        ),
    ]
