# Generated by Django 3.2.4 on 2021-07-11 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('us_state', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usstate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='usstate',
            name='environment',
        ),
    ]
