# Generated by Django 3.0 on 2020-09-28 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0001_initial'),
        ('candidate', '0003_auto_20200920_0108'),
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='candidate',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_relation', to='candidate.Candidate'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='committee',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_relation', to='committee.Committee'),
        ),
        migrations.AlterUniqueTogether(
            name='receipt',
            unique_together={('committee', 'transaction_id')},
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='environment',
        ),
    ]
