# Generated by Django 3.0 on 2020-09-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0002_auto_20200928_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='zip',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
