# Generated by Django 3.0 on 2020-10-03 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0001_initial'),
        ('contributor', '0001_initial'),
        ('receipt', '0003_auto_20200928_0150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['contributor_id', 'year', 'amount'], 'verbose_name': 'receipt', 'verbose_name_plural': 'receipts'},
        ),
        migrations.AddField(
            model_name='receipt',
            name='contributor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_relation', to='contributor.Contributor'),
        ),
        migrations.AlterUniqueTogether(
            name='receipt',
            unique_together={('committee', 'contributor', 'transaction_id')},
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='city',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='state',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='zip',
        ),
    ]
