# Generated by Django 3.0 on 2020-10-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0004_auto_20201003_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='candidate',
        ),
    ]
