# Generated by Django 3.2.5 on 2021-07-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('year', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='year',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='year',
            name='environment',
        ),
    ]
