parents:
    - module: host
      profile: aws/config

config:
    aws_importer_ebs_type: gp2
    aws_importer_ebs_data_size: 10
    aws_importer_ebs_iops: null
    aws_importer_ebs_encrypted: false
    aws_importer_data_device: /dev/xvdb

    aws_service_subnet_names: "#keys(@aws_service_subnets || @aws_service_subnet_prefix);"

server:
    fec-dev:
        count: 1
        provider: ec2
        network: "@aws_network_names[0]"
        subnet: "@aws_service_subnet_names[0]"
        image: "@aws_ubuntu_image[<network>]"
        ssh_port: "@ssh_port"
        user: "@aws_ubuntu_user"
        machine: "@aws_service_worker_machine"
        tenancy: "@aws_service_worker_tenancy"
        monitoring: "@aws_service_worker_monitoring"
        ebs_optimized: "@aws_service_worker_ebs_optimized"
        groups: "@service_group"
        volumes:
            "/var/data":
                provider: aws_ebs
                type: ext4
                location: "@aws_importer_data_device"
                ebs_type: "@aws_importer_ebs_type"
                ebs_size: "@aws_importer_ebs_data_size"
                ebs_iops: "@aws_importer_ebs_iops"
                ebs_encrypted: "@aws_importer_ebs_encrypted"
        firewalls:
            - internet
            - ssh-external
            - "@{data_firewall_prefix}@{database_name}"

post_run:
    credentials:
        command: server rotate
        server_search: name.startswith=fec-dev

    user-environment:
        requires: credentials
        module: cluster
        task: user-environment
        servers: name.startswith=fec-dev

    docker:
        requires: credentials
        module: docker
        task: docker
        servers: name.startswith=fec-dev
        ntp_timezone: "@primary_timezone"
        app_user: "@aws_ubuntu_user"
        docker_users:
            - "@aws_ubuntu_user"

    zimagi:
        requires: docker
        module: host
        task: zimagi-cli
        servers: name.startswith=fec-dev
