# Generated by Django 3.2.5 on 2021-07-13 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('us_city', '0001_initial'),
        ('us_zipcode', '0001_initial'),
        ('employer', '0001_initial'),
        ('occupation', '0001_initial'),
        ('us_state', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('contributor_id', models.CharField(max_length=256, null=True)),
                ('first_name', models.CharField(max_length=256, null=True)),
                ('middle_name', models.CharField(max_length=256, null=True)),
                ('last_name', models.CharField(max_length=256, null=True)),
                ('address_1', models.CharField(max_length=256, null=True)),
                ('address_2', models.CharField(max_length=256, null=True)),
                ('city', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contributor_relation', to='us_city.uscity')),
                ('employer', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contributor_relation', to='employer.employer')),
                ('occupation', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contributor_relation', to='occupation.occupation')),
                ('state', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contributor_relation', to='us_state.usstate')),
                ('zipcode', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contributor_relation', to='us_zipcode.uszipcode')),
            ],
            options={
                'verbose_name': 'contributor',
                'verbose_name_plural': 'contributors',
                'db_table': 'fec_contributor',
                'ordering': ['first_name', 'middle_name', 'last_name'],
                'abstract': False,
            },
        ),
    ]
