# Generated by Django 3.0 on 2020-10-03 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environment', '0002_auto_20190520_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('contributor_id', models.CharField(max_length=256, null=True)),
                ('first_name', models.CharField(max_length=256, null=True)),
                ('middle_name', models.CharField(max_length=256, null=True)),
                ('last_name', models.CharField(max_length=256, null=True)),
                ('address_1', models.CharField(max_length=256, null=True)),
                ('address_2', models.CharField(max_length=256, null=True)),
                ('city', models.CharField(max_length=256, null=True)),
                ('state', models.CharField(max_length=256, null=True)),
                ('zip', models.CharField(max_length=25, null=True)),
                ('employer', models.CharField(max_length=256, null=True)),
                ('occupation', models.CharField(max_length=256, null=True)),
                ('environment', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contributor_relation', to='environment.Environment')),
            ],
            options={
                'verbose_name': 'contributor',
                'verbose_name_plural': 'contributors',
                'db_table': 'fec_contributor',
                'ordering': ['first_name', 'middle_name', 'last_name'],
                'abstract': False,
                'unique_together': {('environment', 'contributor_id')},
            },
        ),
    ]
