# Generated by Django 3.0 on 2020-10-04 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='zip',
        ),
    ]
