# Generated by Django 3.0 on 2020-10-04 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('us_city', '0001_initial'),
        ('employer', '0001_initial'),
        ('occupation', '0001_initial'),
        ('us_zipcode', '0001_initial'),
        ('us_state', '0001_initial'),
        ('contributor', '0002_remove_contributor_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='zipcode',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contributor_relation', to='us_zipcode.USZipcode'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='city',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contributor_relation', to='us_city.USCity'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='employer',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contributor_relation', to='employer.Employer'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='occupation',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contributor_relation', to='occupation.Occupation'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='state',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contributor_relation', to='us_state.USState'),
        ),
    ]
